name: @name@
description: @description@
author: Chris (Coaster3000 | Coaster4321)
authors: [ProgrammerDan, PatchyKnowly, Mr_Little_Kitty]
website: @website@
version: @version@-@apiversion@
main: @mainClass@
commands:
 reloadWorldInfo:
  description: Execute the current debug code.
permissions:
 wuuid.reload:
  description: Controls access to configuration reloading.
  default: op
